### ISSUE TITLE
Write Block descriptions

### ISSUE THREAD

**Issue by MaikePaetzel** [01rfcberlin/robocup-blockly#15]
Write proper block descriptions so if the children hover over a block, they understand what this block is actually doing.

**Comment by lyamiver** [comment]
The first block - handles the addition of a robot where you need to enter two numeric entries for the x and y position. This block handles the addition of the robot.
If you hover the mouse cursor over the block, it will display the message: "Adds a new robot to the field".
The second unit - handles the movement of the robot, where you need to enter 2 numbers for the x and y integer position of this robot. This block is where the robot is moved. If you put the mouse cursor on the block, it will display the message: "Moves the robot across the field".

Translated with www.DeepL.com/Translator (free version)
