### ISSUE TITLE
5: resetting while moving: TypeError: current_robot.target is undefined

### ISSUE THREAD

**Issue by froschy** [01rfcberlin/robocup-blockly#33]

**Comment by froschy** [comment]
![grafik](https://user-images.githubusercontent.com/69001402/115299159-bd4efc00-a15e-11eb-91ba-8144c96e9e50.png)


after 2nd step, between movement

**Comment by MaikePaetzel** [comment]
So my commit fixed the syntax error, but now the robot position isn't reset correctly

**Comment by schra** [comment]
cannot reproduce this. we changed so much in this code, i suspect this error is gone. otherwise, please re-open the issue
