### ISSUE TITLE
6: syntax error when resetting while moving. Unexpected token (2:9)

### ISSUE THREAD

**Issue by froschy** [01rfcberlin/robocup-blockly#41]
![grafik](https://user-images.githubusercontent.com/69001402/115302204-75ca6f00-a162-11eb-9446-514910d16132.png)

**Comment by MaikePaetzel** [comment]
Duplicate #40

**Comment by froschy** [comment]
![grafik](https://user-images.githubusercontent.com/69001402/115471942-1db26c00-a239-11eb-9f24-69ff82a6578c.png)

**Comment by froschy** [comment]
![grafik](https://user-images.githubusercontent.com/69001402/115471954-24d97a00-a239-11eb-89e5-9f00e295374b.png)
