### ISSUE TITLE
5:6: after succesful lvl completion "reset" does not switch to "code ausführen" when changing to next level 

### ISSUE THREAD

**Issue by froschy** [01rfcberlin/robocup-blockly#59]
![grafik](https://user-images.githubusercontent.com/69001402/115472662-99f97f00-a23a-11eb-9907-1c0ef466f5f3.png)

**Comment by schra** [comment]
Please test this again with the newest commit (https://github.com/MaikePaetzel/robocup-blockly-demo/commit/421505a7d59eee6181f8fea8da2d2b982c4e5a2f). Can't reproduce

**Comment by froschy** [comment]
I testet today on old commit, still occured. Cannot reproduce it with newest commit either.
